import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

export const metadata = {
  title: "Terms & Conditions - GHALIB",
  description: "Terms and Conditions for GHALIB - Your poetry creation platform",
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0B0E15]">
      <Navbar />

      <section className="pt-24 pb-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-bold text-[#A88C63] mb-8">Terms & Conditions</h1>

          <div className="prose prose-invert max-w-none space-y-8">
            <div className="bg-[#12161f] rounded-lg p-6 border border-[#A88C63]/20">
              <h2 className="text-xl font-semibold text-[#A88C63] mb-4">User Content Ownership</h2>
              <p className="text-[#E4D9C8]/80 leading-relaxed">
                You retain full ownership of all poetry and creative content you create using GHALIB. By using our
                platform, you grant us a non-exclusive license to display and store your content solely for the purpose
                of providing our services.
              </p>
            </div>

            <div className="bg-[#12161f] rounded-lg p-6 border border-[#A88C63]/20">
              <h2 className="text-xl font-semibold text-[#A88C63] mb-4">Prohibited Content</h2>
              <p className="text-[#E4D9C8]/80 leading-relaxed mb-4">
                Users agree not to create, share, or distribute content that:
              </p>
              <ul className="list-disc list-inside text-[#E4D9C8]/80 space-y-2">
                <li>Promotes hate, discrimination, or violence against any individual or group</li>
                <li>Contains plagiarized content or violates intellectual property rights</li>
                <li>Includes explicit, harmful, or illegal material</li>
                <li>Harasses, threatens, or intimidates other users</li>
              </ul>
            </div>

            <div className="bg-[#12161f] rounded-lg p-6 border border-[#A88C63]/20">
              <h2 className="text-xl font-semibold text-[#A88C63] mb-4">Content Moderation</h2>
              <p className="text-[#E4D9C8]/80 leading-relaxed">
                GHALIB reserves the right to review, moderate, and remove any content that violates these terms. We may
                suspend or terminate accounts that repeatedly violate our guidelines without prior notice.
              </p>
            </div>

            <div className="bg-[#12161f] rounded-lg p-6 border border-[#A88C63]/20">
              <h2 className="text-xl font-semibold text-[#A88C63] mb-4">AI-Generated Content</h2>
              <p className="text-[#E4D9C8]/80 leading-relaxed">
                Content generated by our AI is provided as creative inspiration. While we strive for originality, we
                cannot guarantee that AI-generated content is unique or free from similarity to existing works.
              </p>
            </div>

            <div className="bg-[#12161f] rounded-lg p-6 border border-[#A88C63]/20">
              <h2 className="text-xl font-semibold text-[#A88C63] mb-4">Service Availability</h2>
              <p className="text-[#E4D9C8]/80 leading-relaxed">
                We aim to provide uninterrupted service but do not guarantee continuous availability. We may modify,
                suspend, or discontinue features with reasonable notice when possible.
              </p>
            </div>

            <div className="bg-[#12161f] rounded-lg p-6 border border-[#A88C63]/20">
              <h2 className="text-xl font-semibold text-[#A88C63] mb-4">Limitation of Liability</h2>
              <p className="text-[#E4D9C8]/80 leading-relaxed">
                GHALIB is provided "as is" without warranties of any kind. We are not liable for any indirect,
                incidental, or consequential damages arising from your use of our services.
              </p>
            </div>
          </div>

          <p className="text-[#E4D9C8]/50 text-sm mt-8">Last updated: {new Date().toLocaleDateString()}</p>
        </div>
      </section>

      <Footer />
    </main>
  )
}
